Add meeting info and link to draft spec to Readme
w3c-ccg/did-pkh pull request #13
Opened 2021-11-23 15:38 UTC by bumblefudge

2021-11-23 18:10 UTC, clehner commented on README.md
> +Regular meetings for this CCG work item will be held every two weeks on Thursdays at 1.30PM Eastern Time, on a [workitem-specific jitsi room](meet.w3c-ccg.org/didpkh) hosted by the CCG.  Minutes will
```suggestion
Regular meetings for this CCG work item will be held every two weeks on Thursdays at 1.30PM Eastern Time, on a [workitem-specific jitsi room](https://meet.w3c-ccg.org/didpkh) hosted by the CCG.  Minutes will be published the same way as other work items.  
```

2021-11-25 13:02 UTC, bumblefudge commented
Just to clarify first meeting 2 Dec, not Thanksgiving day :D

2021-11-30 01:55 UTC, clehner approved these changes

2021-11-30 16:17 UTC, clehner approved these changes

2021-11-30 18:11 UTC, TallTed requested changes

2021-11-30 18:11 UTC, TallTed commented on README.md
> +Our **standing agenda** is first PR review, then issue review (prioritized by labels, then by stalest-first).
```suggestion
Our **standing agenda** is first [PR](https://github.com/w3c-ccg/did-pkh/pulls) review, then 
[issue](https://github.com/w3c-ccg/did-pkh/issues) review (prioritized by labels, then by 
[stalest-first](https://github.com/w3c-ccg/did-pkh/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc)). 
```

2021-11-30 18:11 UTC, TallTed commented on README.md
> +Regular meetings for this CCG work item will be held every two weeks on Thursdays at 1.30PM Eastern Time, on a
```suggestion
Regular meetings for this CCG work item will be held every two weeks on Thursdays at [1.30PM Eastern Time](https://www.timeanddate.com/worldclock/), on a 
```

2021-11-30 18:11 UTC, TallTed commented on README.md
> + n up-to-date agenda for the upcoming meeting(s). We are also glad to take requests for older issues to
```suggestion
an up-to-date agenda for the upcoming meeting(s). We are also glad to take requests for older issues to 
```

2021-11-30 21:43 UTC, merged